### ISSUE TITLE
How can I get new parent_id onSortCompleted?

### ISSUE THREAD

**Issue by a13xh7** [ahamed/treeSortable#1]
Hello.

How can I get new parent_id onSortCompleted?

Or when I creating child brach, how can I get parent data like id?

**Comment by netglobaltr** [comment]
unfortunately no response. :(

**Comment by ahamed** [comment]
Hello,
Please pull the latest code, and you can get the __parent id__ from the `onSortCompleted` function.
In the `onSortCompleted` function we are giving you two parameters-
- event : the `sortCompleted` custom event.
- ui : the jQuery sortable's ui object.

Inside the `ui` object you will get the `item` property which is the dragging item (the item you have been dragging). and from the `ui.item` you can get the `parent` data attribute.

```js
sortable.onSortCompleted(async (event, ui) => {
  console.log(ui.item.data('parent')); // will return you the parent_id.
});
```
